<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE mitgliederliste [
	<!ELEMENT mitgliederliste (mitglied*)>
	<!ELEMENT mitglied (name, email, xmpp, studienbeginn, studiengang, beschreibung, projekte, status)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT xmpp (#PCDATA)>
	<!ELEMENT studienbeginn (#PCDATA)>
	<!ELEMENT studiengang (#PCDATA)>
	<!ELEMENT beschreibung (#PCDATA)>
	<!ELEMENT projekte (projekt*)>
	<!ELEMENT projekt (#PCDATA)>
]>

<mitgliederliste>
	<mitglied>
		<name>First Member</name>
		<projekte>
			<projekt>P0</projekt>
		</projekte>
		<status>member</status>
	</mitglied>

	<mitglied>
		<name>First Collaborator</name>
		<projekte>
			<projekt>P1</projekt>
		</projekte>
		<status>collaborator</status>
	</mitglied>
</mitgliederliste>
